project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - index.qmd
    - settings.qmd
    - workflow.qmd
    - cli-commands.qmd 
    - the_dockerfile.qmd
    - build.qmd
    - run.qmd
    - docker_compose.qmd

website:
  title: "sdsu-docker-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents: 
      - index.qmd
      - settings.qmd
      - workflow.qmd
      - cli-commands.qmd
      - the_dockerfile.qmd
      - build.qmd
      - run.qmd
      - docker_compose.qmd 

format:
  html:
    theme: default
    css: styles.css
    toc: true



