project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - 01-settings.qmd
    - 02-workflow.qmd
    - 03-the_dockerfile.qmd
    - 04-build.qmd
    - 05-run.qmd
    - 06-docker_compose.qmd

website:
  title: "sdsu-docker-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents: 
      - index.qmd
      - 01-settings.qmd
      - 02-workflow.qmd
      - 03-the_dockerfile.qmd
      - 04-build.qmd
      - 05-run.qmd
      - 06-docker_compose.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



